### PR TITLE
Add support for symlinks

### LINKED ISSUE #78: include support for symlinks
Is it possible to include support for symlinks at graylog-plugin-collector/src/web/collector-configuration/EditInputFields.jsx?

Or is it any workaround to get symlinks enabled?

For reference, this is the issue I'm facing https://discuss.elastic.co/t/how-to-enable-symlinks/126852

Thx!

### PR DESCRIPTION
**Pull request by ayrodrig**
Fixes #78.

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanks for the PR!
All other checkboxes are not `required` would you mind changing this?

**Comment by ayrodrig** [comment]
Not sure what to do about the jenkins check that failed. Is it required any action from my side? From details I just get "Access Denied. ayrodrig is missing the Overall/Read permission". I think I granted the corresponding permission.

**Comment by mariussturm** [comment]
It fails because the `Input`-tag doesn't close properly.

**Comment by mariussturm** [comment]
Thank you Sir! LGTM!

**Pull request merged**
