### PR TITLE
Integrate audit log

### PR DESCRIPTION
**Pull request by edmundoa**
This PR adds the necessary changes to integrate the audit log with the collector.

### CODE REVIEW

**Comment by mariussturm** [comment]
Thanka a lot! Looks fine for me, just the `collector_registration:update` is only a ping signal from each collector. I think that should not create an audit event?

**Comment by bernd** [comment]
> Thanka a lot! Looks fine for me, just the collector_registration:update is only a ping signal from each collector. I think that should not create an audit event?

Aye, that's probably too much.

**Comment by edmundoa** [comment]
Changing it! 👍

**Comment by mariussturm** [comment]
Thanks again! 👍

**Pull request merged**
